import { createVerifiedCatalogProvider } from "./catalog.js";

const ROOT = "https://github.com/godotengine/godot-demo-projects/tree/master";
const demo = (path: string) => `${ROOT}/${path}`;

export const godotDemosProvider = createVerifiedCatalogProvider(
  "godotdemos",
  "Godot Demo Projects",
  {
    license: "MIT",
    licenseSource: "https://github.com/godotengine/godot-demo-projects/blob/master/LICENSE.md",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false
  },
  [
    { id: "godot-2d-demos", name: "Godot 2D Demo Collection", sourceUrl: demo("2d"), description: "Official Godot 2D demo projects and implementation examples.", categories: ["Code", "Starter", "2D"], tags: ["godot", "demo", "2d", "starter", "gameplay"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "code", "example"], gameGenres: ["multiple"] },
    { id: "godot-3d-demos", name: "Godot 3D Demo Collection", sourceUrl: demo("3d"), description: "Official Godot 3D demo projects and implementation examples.", categories: ["Code", "Starter", "3D"], tags: ["godot", "demo", "3d", "starter", "gameplay"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "code", "example"], gameGenres: ["multiple"] },
    { id: "godot-audio-demos", name: "Godot Audio Demo Collection", sourceUrl: demo("audio"), description: "Official Godot audio and sound-system demos.", categories: ["Code", "Audio"], tags: ["godot", "audio", "sound", "demo"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["audio-system", "code", "example"] },
    { id: "godot-gui-demos", name: "Godot GUI Demo Collection", sourceUrl: demo("gui"), description: "Official Godot UI and Control-node demos.", categories: ["Code", "UI"], tags: ["godot", "gui", "ui", "control", "demo"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["ui", "code", "example"] },
    { id: "godot-compute-demos", name: "Godot Compute Demo Collection", sourceUrl: demo("compute"), description: "Official Godot compute and GPU programming demos.", categories: ["Code", "Shader"], tags: ["godot", "compute", "gpu", "shader", "demo"], engine: ["godot"], dimension: "code", formats: ["gdscript", "glsl"], assetTypes: ["shader", "code", "example"] },

    { id: "godot-dodge-the-creeps", name: "Godot Dodge the Creeps", sourceUrl: demo("2d/dodge_the_creeps"), description: "Complete official 2D tutorial game useful as a compact playable-project starter/reference.", categories: ["Code", "Starter", "2D", "Game"], tags: ["godot", "2d", "starter", "game", "complete", "arcade", "survival", "enemy", "spawn"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["arcade", "survival"] },
    { id: "godot-2d-platformer", name: "Godot 2D Platformer Demo", sourceUrl: demo("2d/platformer"), description: "Official complete 2D platformer demo with reusable character and platform-game structure.", categories: ["Code", "Starter", "2D", "Game"], tags: ["godot", "2d", "starter", "game", "complete", "platformer", "character", "physics"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["platformer"] },
    { id: "godot-2d-physics-platformer", name: "Godot 2D Physics Platformer", sourceUrl: demo("2d/physics_platformer"), description: "Official 2D physics platformer demonstrating physically driven platform gameplay.", categories: ["Code", "Starter", "2D", "Physics"], tags: ["godot", "2d", "starter", "platformer", "physics", "character"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["platformer"] },
    { id: "godot-2d-rpg", name: "Godot 2D Role Playing Game", sourceUrl: demo("2d/role_playing_game"), description: "Official 2D role-playing game demo suitable as a reference for RPG structure and interactions.", categories: ["Code", "Starter", "2D", "RPG"], tags: ["godot", "2d", "starter", "game", "complete", "rpg", "role-playing", "character", "interaction"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["rpg", "adventure"] },
    { id: "godot-2d-pong", name: "Godot Pong Demo", sourceUrl: demo("2d/pong"), description: "Small complete Pong-style game demonstrating input, collision and score/game-loop structure.", categories: ["Code", "Starter", "2D", "Game"], tags: ["godot", "2d", "starter", "game", "complete", "pong", "arcade", "physics"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["arcade"] },
    { id: "godot-2d-isometric", name: "Godot Isometric Demo", sourceUrl: demo("2d/isometric"), description: "Official 2D isometric rendering/map example useful for isometric game prototypes.", categories: ["Code", "Starter", "2D", "Isometric"], tags: ["godot", "2d", "starter", "isometric", "map", "tilemap", "game"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "code", "example"], gameGenres: ["rpg", "strategy", "simulation"] },
    { id: "godot-2d-fsm", name: "Godot Finite State Machine Demo", sourceUrl: demo("2d/finite_state_machine"), description: "Official finite-state-machine example for reusable gameplay/AI state logic.", categories: ["Code", "AI", "2D"], tags: ["godot", "2d", "finite", "state", "machine", "fsm", "ai", "behavior", "character"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["ai-system", "state-machine", "code", "example"] },
    { id: "godot-2d-navigation", name: "Godot 2D Navigation Demo", sourceUrl: demo("2d/navigation"), description: "Official 2D navigation/pathfinding example.", categories: ["Code", "AI", "2D"], tags: ["godot", "2d", "navigation", "pathfinding", "ai", "movement"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["navigation", "pathfinding", "ai-system", "code", "example"] },
    { id: "godot-2d-astar", name: "Godot 2D AStar Navigation Demo", sourceUrl: demo("2d/navigation_astar"), description: "Official AStar-based 2D pathfinding example.", categories: ["Code", "AI", "2D"], tags: ["godot", "2d", "astar", "a-star", "navigation", "pathfinding", "ai"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["navigation", "pathfinding", "ai-system", "code", "example"] },
    { id: "godot-2d-dynamic-tilemap", name: "Godot Dynamic TileMap Layers Demo", sourceUrl: demo("2d/dynamic_tilemap_layers"), description: "Official dynamic TileMap-layer example useful for procedural/changing 2D worlds.", categories: ["Code", "2D", "World"], tags: ["godot", "2d", "tilemap", "dynamic", "procedural", "world", "map"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["procedural-generation", "map-system", "code", "example"] },

    { id: "godot-3d-platformer", name: "Godot 3D Platformer Demo", sourceUrl: demo("3d/platformer"), description: "Official 3D platformer project useful as a concrete starter/reference for third-person movement and platform gameplay.", categories: ["Code", "Starter", "3D", "Game"], tags: ["godot", "3d", "starter", "game", "complete", "platformer", "character", "third-person"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["platformer", "action"] },
    { id: "godot-3d-squash-creeps", name: "Godot Squash the Creeps", sourceUrl: demo("3d/squash_the_creeps"), description: "Complete official 3D tutorial game demonstrating movement, enemies, spawning and gameplay loop.", categories: ["Code", "Starter", "3D", "Game"], tags: ["godot", "3d", "starter", "game", "complete", "enemy", "spawn", "character", "action"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "game", "code", "example"], gameGenres: ["action", "arcade"] },
    { id: "godot-3d-truck-town", name: "Godot Truck Town", sourceUrl: demo("3d/truck_town"), description: "Official 3D vehicle/truck project useful as a vehicle-driving and physics implementation reference.", categories: ["Code", "Starter", "3D", "Vehicle"], tags: ["godot", "3d", "starter", "vehicle", "driving", "truck", "physics", "game"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["starter", "vehicle-system", "physics", "game", "code", "example"], gameGenres: ["driving", "simulation"] },
    { id: "godot-3d-kinematic-character", name: "Godot 3D Kinematic Character", sourceUrl: demo("3d/kinematic_character"), description: "Official reusable 3D character-controller/movement example.", categories: ["Code", "3D", "Character"], tags: ["godot", "3d", "character", "controller", "movement", "kinematic", "third-person"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["character-controller", "code", "example"] },
    { id: "godot-3d-navigation", name: "Godot 3D Navigation Demo", sourceUrl: demo("3d/navigation"), description: "Official 3D navigation/pathfinding example.", categories: ["Code", "AI", "3D"], tags: ["godot", "3d", "navigation", "pathfinding", "ai", "movement"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["navigation", "pathfinding", "ai-system", "code", "example"] },
    { id: "godot-3d-navigation-chunks", name: "Godot 3D Navigation Mesh Chunks", sourceUrl: demo("3d/navigation_mesh_chunks"), description: "Official chunked navigation-mesh example useful for larger/dynamic worlds.", categories: ["Code", "AI", "3D", "World"], tags: ["godot", "3d", "navigation", "navmesh", "chunks", "pathfinding", "world", "procedural"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["navigation", "pathfinding", "procedural-generation", "code", "example"] },
    { id: "godot-3d-voxel", name: "Godot 3D Voxel Demo", sourceUrl: demo("3d/voxel"), description: "Official voxel example useful for block/voxel world and procedural-content experiments.", categories: ["Code", "3D", "World"], tags: ["godot", "3d", "voxel", "block", "procedural", "world", "generation"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["procedural-generation", "world-system", "code", "example"], gameGenres: ["sandbox", "survival"] },
    { id: "godot-3d-waypoints", name: "Godot 3D Waypoints Demo", sourceUrl: demo("3d/waypoints"), description: "Official 3D waypoint/movement reference for NPCs and route-following systems.", categories: ["Code", "AI", "3D"], tags: ["godot", "3d", "waypoint", "ai", "npc", "path", "movement"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["ai-system", "navigation", "code", "example"] },
    { id: "godot-3d-procedural-materials", name: "Godot Procedural Materials Demo", sourceUrl: demo("3d/procedural_materials"), description: "Official procedural-material example for 3D rendering/content workflows.", categories: ["Code", "Shader", "3D"], tags: ["godot", "3d", "procedural", "material", "shader", "rendering"], engine: ["godot"], dimension: "code", formats: ["gdscript", "glsl", "tscn"], assetTypes: ["shader", "procedural-generation", "code", "example"] },
    { id: "godot-3d-particles", name: "Godot 3D Particles Demo", sourceUrl: demo("3d/particles"), description: "Official 3D particles/VFX example.", categories: ["Code", "VFX", "3D"], tags: ["godot", "3d", "particles", "vfx", "effect", "shader"], engine: ["godot"], dimension: "code", formats: ["gdscript", "tscn"], assetTypes: ["vfx", "shader", "code", "example"] }
  ],
  { verificationStatus: "verified", verifiedAt: "2026-08-16T00:00:00.000Z" }
);
