import { createCc0CatalogProvider } from "./catalog.js";

export const kenneyProvider = createCc0CatalogProvider(
  "kenney",
  "Kenney",
  "https://kenney.nl/support",
  [
    { id: "rpg-base", name: "RPG Base", sourceUrl: "https://kenney.nl/assets/rpg-base", categories: ["2D"], tags: ["rpg", "tiles"], dimension: "2D", style: ["cartoon"], formats: ["png"], assetTypes: ["tileset", "environment"], gameGenres: ["rpg"] },
    { id: "platformer-characters", name: "Platformer Characters", sourceUrl: "https://kenney.nl/assets/platformer-characters", categories: ["2D"], tags: ["platformer", "characters"], dimension: "2D", style: ["cartoon"], formats: ["png"], assetTypes: ["character"], gameGenres: ["platformer"], animated: true },
    { id: "prototype-kit", name: "Prototype Kit", sourceUrl: "https://kenney.nl/assets/prototype-kit", categories: ["3D"], tags: ["prototype", "vehicle", "building", "character"], dimension: "3D", style: ["prototype", "low-poly"], formats: ["fbx", "obj", "gltf"], assetTypes: ["environment", "vehicle", "character"] },
    { id: "tower-defense-top-down", name: "Tower Defense (Top-Down)", sourceUrl: "https://kenney.nl/assets/tower-defense-top-down", categories: ["2D"], tags: ["tower-defense", "top-down", "weapon"], dimension: "2D", formats: ["png"], assetTypes: ["environment", "weapon", "ui"], gameGenres: ["tower-defense"] },
    { id: "pixel-vehicle-pack", name: "Pixel Vehicle Pack", sourceUrl: "https://kenney.nl/assets/pixel-vehicle-pack", categories: ["2D"], tags: ["vehicle", "car", "pixel"], dimension: "2D", style: ["pixel"], formats: ["png"], assetTypes: ["vehicle"], gameGenres: ["racing", "top-down"] },
    { id: "car-kit", name: "Car Kit", sourceUrl: "https://kenney.nl/assets/car-kit", categories: ["3D", "Transport"], tags: ["vehicle", "car", "transport"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "gltf"], assetTypes: ["vehicle"], gameGenres: ["racing"] },
    { id: "pixel-platformer", name: "Pixel Platformer", sourceUrl: "https://kenney.nl/assets/pixel-platformer", categories: ["2D", "Pixel Platformer"], tags: ["platformer", "pixel", "tiles"], dimension: "2D", style: ["pixel"], formats: ["png"], assetTypes: ["tileset", "environment"], gameGenres: ["platformer"] },
    { id: "blaster-kit", name: "Blaster Kit", sourceUrl: "https://kenney.nl/assets/blaster-kit", categories: ["3D"], tags: ["weapon", "blaster", "animation"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "gltf"], assetTypes: ["weapon"], gameGenres: ["shooter"], animated: true },
    { id: "ui-pack", name: "UI Pack", sourceUrl: "https://kenney.nl/assets/ui-pack", categories: ["2D", "UI"], tags: ["button", "panel", "slider", "interface"], dimension: "2D", style: ["clean"], formats: ["png"], assetTypes: ["ui"] },
    { id: "ui-pack-rpg-expansion", name: "UI Pack (RPG Expansion)", sourceUrl: "https://kenney.nl/assets/ui-pack-rpg-expansion", categories: ["2D", "UI"], tags: ["button", "panel", "slider", "rpg", "interface"], dimension: "2D", formats: ["png"], assetTypes: ["ui"], gameGenres: ["rpg"] },
    { id: "ui-pack-adventure", name: "UI Pack - Adventure", sourceUrl: "https://kenney.nl/assets/ui-pack-adventure", categories: ["2D", "UI"], tags: ["button", "panel", "slider", "interface"], dimension: "2D", style: ["adventure"], formats: ["png"], assetTypes: ["ui"], gameGenres: ["adventure"] },
    { id: "pixel-ui-pack", name: "Pixel UI Pack", sourceUrl: "https://kenney.nl/assets/pixel-ui-pack", categories: ["2D", "UI"], tags: ["pixel", "panel", "button"], dimension: "2D", style: ["pixel"], formats: ["png"], assetTypes: ["ui"] },
    { id: "ui-pack-pixel-adventure", name: "UI Pack - Pixel Adventure", sourceUrl: "https://kenney.nl/assets/ui-pack-pixel-adventure", categories: ["2D", "UI"], tags: ["button", "panel", "slider", "interface", "pixel"], dimension: "2D", style: ["pixel", "adventure"], formats: ["png"], assetTypes: ["ui"], gameGenres: ["adventure"] },
    { id: "ui-pack-sci-fi", name: "UI Pack - Sci-Fi", sourceUrl: "https://kenney.nl/assets/ui-pack-sci-fi", categories: ["2D", "UI"], tags: ["button", "panel", "slider", "space", "sci-fi", "interface"], dimension: "2D", style: ["sci-fi"], formats: ["png"], assetTypes: ["ui"], gameGenres: ["sci-fi"] },
    { id: "interface-sounds", name: "Interface Sounds", sourceUrl: "https://kenney.nl/assets/interface-sounds", categories: ["Audio", "UI Audio"], tags: ["interface", "click", "button"], dimension: "audio", formats: ["ogg", "wav"], assetTypes: ["sfx", "ui-audio"], gameGenres: ["general"] },
    { id: "ui-audio", name: "UI Audio", sourceUrl: "https://kenney.nl/assets/ui-audio", categories: ["Audio", "UI Audio"], tags: ["button", "switch", "click", "interface"], dimension: "audio", formats: ["ogg", "wav"], assetTypes: ["sfx", "ui-audio"], gameGenres: ["general"] },
    { id: "sci-fi-sounds", name: "Sci-Fi Sounds", sourceUrl: "https://kenney.nl/assets/sci-fi-sounds", categories: ["Audio", "SFX"], tags: ["sci-fi", "space", "engine", "laser"], dimension: "audio", style: ["sci-fi"], formats: ["ogg", "wav"], assetTypes: ["sfx"], gameGenres: ["sci-fi", "shooter", "space"] },
    { id: "digital-audio", name: "Digital Audio", sourceUrl: "https://kenney.nl/assets/digital-audio", categories: ["Audio", "SFX"], tags: ["digital", "space", "laser"], dimension: "audio", style: ["digital", "sci-fi"], formats: ["ogg", "wav"], assetTypes: ["sfx"], gameGenres: ["sci-fi", "arcade"] },
    { id: "impact-sounds", name: "Impact Sounds", sourceUrl: "https://kenney.nl/assets/impact-sounds", categories: ["Audio", "SFX"], tags: ["impact", "foley", "collision"], dimension: "audio", formats: ["ogg", "wav"], assetTypes: ["sfx", "foley"], gameGenres: ["action", "general"] },
    { id: "music-jingles", name: "Music Jingles", sourceUrl: "https://kenney.nl/assets/music-jingles", categories: ["Audio", "Music"], tags: ["music", "jingle", "stinger"], dimension: "audio", formats: ["ogg", "wav"], assetTypes: ["music", "jingle"], gameGenres: ["arcade", "casual", "general"] },
    { id: "voiceover-pack", name: "Voiceover Pack", sourceUrl: "https://kenney.nl/assets/voiceover-pack/", categories: ["Audio", "Voiceover"], tags: ["voice", "female", "male", "announcer"], dimension: "audio", formats: ["ogg", "wav"], assetTypes: ["voiceover"], gameGenres: ["general"] },
    { id: "roguelike-rpg-pack", name: "Roguelike/RPG Pack", sourceUrl: "https://kenney.nl/assets/roguelike-rpg-pack", categories: ["2D"], tags: ["rpg", "tile", "town", "furniture", "roguelike", "pixel"], dimension: "2D", style: ["pixel"], formats: ["png"], assetTypes: ["tileset", "environment", "ui"], gameGenres: ["rpg", "roguelike"], resolution: "16x16" }
  ]
);
