import { createCc0CatalogProvider } from "./catalog.js";

const ROOT = "https://quaternius.com/";
const pack = (slug: string) => `https://quaternius.com/packs/${slug}.html`;

export const quaterniusProvider = createCc0CatalogProvider(
  "quaternius",
  "Quaternius",
  "https://quaternius.com/faq.html",
  [
    { id: "downtown-city-megakit", name: "Downtown City MegaKit", sourceUrl: pack("downtowncitymegakit"), description: "300+ modular urban environment pieces for modern downtown/city blocks, streets, facades and props.", categories: ["3D", "Environment", "City"], tags: ["city", "downtown", "urban", "road", "street", "building", "modular", "props"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["low-poly", "urban", "stylized"], formats: ["fbx", "blend", "gltf"], assetTypes: ["environment", "building", "prop"], gameGenres: ["simulation", "action", "rpg"] },
    { id: "universal-animation-library-2", name: "Universal Animation Library 2", sourceUrl: pack("universalanimationlibrary2"), description: "130+ retargetable humanoid animations covering combat, parkour, farming, fishing and zombie locomotion.", categories: ["3D", "Animation", "Characters"], tags: ["animation", "humanoid", "retarget", "combat", "parkour", "farming", "zombie"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["universal"], formats: ["fbx", "blend", "gltf"], assetTypes: ["animation", "character"], gameGenres: ["action", "rpg", "survival"], animated: true },
    { id: "modular-character-outfits-fantasy", name: "Modular Character Outfits - Fantasy", sourceUrl: pack("modularcharacteroutfitsfantasy"), description: "Modular fantasy outfits compatible with Quaternius universal humanoid characters and retargetable rigs.", categories: ["3D", "Characters", "Fantasy"], tags: ["character", "outfit", "modular", "fantasy", "knight", "medieval", "retarget"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["stylized", "fantasy", "medieval"], formats: ["fbx", "blend", "gltf"], assetTypes: ["character", "clothing"], gameGenres: ["rpg", "adventure"], animated: true },
    { id: "universal-base-characters", name: "Universal Base Characters", sourceUrl: pack("universalbasecharacters"), description: "Game-ready male/female humanoid base characters with hairstyles and a retargetable humanoid rig.", categories: ["3D", "Characters"], tags: ["character", "humanoid", "base", "retarget", "rigged", "hair"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["stylized"], formats: ["fbx", "blend", "gltf"], assetTypes: ["character"], gameGenres: ["rpg", "action", "adventure"], animated: true },
    { id: "fantasy-props-megakit", name: "Fantasy Props MegaKit", sourceUrl: pack("fantasypropsmegakit"), description: "200+ optimized medieval/fantasy props including weapons, tools, furniture, potions, markets and breakables.", categories: ["3D", "Props", "Fantasy"], tags: ["fantasy", "medieval", "weapon", "tool", "furniture", "potion", "market", "prop"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["low-poly", "fantasy", "medieval"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["prop", "weapon", "environment"], gameGenres: ["rpg", "adventure", "survival"] },
    { id: "universal-animation-library", name: "Universal Animation Library", sourceUrl: pack("universalanimationlibrary"), description: "120+ universal humanoid animations for locomotion, combat, guns, swimming, crawling and emotes.", categories: ["3D", "Animation", "Characters"], tags: ["animation", "humanoid", "retarget", "locomotion", "combat", "gun", "emote"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["universal"], formats: ["fbx", "glb", "blend"], assetTypes: ["animation", "character"], gameGenres: ["action", "rpg", "shooter"], animated: true },
    { id: "medieval-village-megakit", name: "Medieval Village MegaKit", sourceUrl: pack("medievalvillagemegakit"), description: "300+ grid-snapped modular medieval village pieces with walls, roofs, stairs, doors, windows and props.", categories: ["3D", "Environment", "Medieval"], tags: ["medieval", "village", "building", "modular", "house", "environment"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["low-poly", "medieval", "fantasy"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["environment", "building", "prop"], gameGenres: ["rpg", "strategy", "adventure"] },
    { id: "scifi-essentials-kit", name: "Sci-Fi Essentials Kit", sourceUrl: pack("scifiessentialskit"), description: "Futuristic essentials including animated robot enemies, guns, screens, crates, holograms and planets.", categories: ["3D", "Sci-Fi"], tags: ["sci-fi", "robot", "enemy", "gun", "hologram", "screen", "prop"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "weapon", "prop", "environment"], gameGenres: ["sci-fi", "shooter", "action"], animated: true },
    { id: "modular-scifi-megakit", name: "Modular Sci-Fi Megakit", sourceUrl: pack("modularscifimegakit"), description: "270+ modular sci-fi corridor, room, alien and platform environment pieces.", categories: ["3D", "Sci-Fi", "Environment"], tags: ["sci-fi", "modular", "environment", "alien", "corridor", "room"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["environment", "building", "prop"], gameGenres: ["sci-fi", "shooter"] },
    { id: "stylized-nature-megakit", name: "Stylized Nature MegaKit", sourceUrl: pack("stylizednaturemegakit"), description: "110+ stylized nature models including trees, plants, flowers, rocks, grass and bushes.", categories: ["3D", "Environment", "Nature"], tags: ["nature", "stylized", "tree", "plant", "rock", "grass", "ghibli"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["stylized", "nature"], formats: ["fbx", "obj", "gltf", "blend"], assetTypes: ["environment", "vegetation", "prop", "shader"], gameGenres: ["adventure", "rpg", "farming"] },
    { id: "zombie-apocalypse-kit", name: "Zombie Apocalypse Kit", sourceUrl: pack("zombieapocalypsekit"), description: "Complete apocalypse-themed art kit with playable characters, zombies, dogs, guns, vehicles and city props.", categories: ["3D", "Game Kit", "Survival"], tags: ["zombie", "survival", "character", "enemy", "weapon", "gun", "vehicle", "city"], dimension: "3D", style: ["low-poly", "apocalypse"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "weapon", "vehicle", "environment"], gameGenres: ["survival", "shooter", "action"], animated: true },
    { id: "ultimate-space-kit", name: "Ultimate Space Kit", sourceUrl: pack("ultimatespacekit"), description: "Large space-game art kit with characters, enemies, mechs, ships, planets, rovers, alien buildings and vegetation.", categories: ["3D", "Game Kit", "Space"], tags: ["space", "sci-fi", "spaceship", "mech", "planet", "rover", "alien", "character"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "vehicle", "environment", "prop"], gameGenres: ["sci-fi", "shooter", "adventure"], animated: true },
    { id: "toon-shooter-game-kit", name: "Toon Shooter Game Kit", sourceUrl: pack("toonshootergamekit"), description: "Complete stylized shooter kit with animated characters, enemies, guns, weapons, tanks and environment assets.", categories: ["3D", "Game Kit", "Shooter"], tags: ["shooter", "toon", "character", "enemy", "gun", "weapon", "tank", "environment"], dimension: "3D", style: ["low-poly", "cartoon"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "weapon", "vehicle", "environment"], gameGenres: ["shooter", "action"], animated: true },
    { id: "ultimate-fantasy-rts", name: "Ultimate Fantasy RTS", sourceUrl: pack("ultimatefantasyrts"), description: "Fantasy/medieval RTS environment kit with staged buildings, towers, mines, farms, markets, ports and nature assets.", categories: ["3D", "Strategy", "Medieval"], tags: ["rts", "strategy", "medieval", "fantasy", "building", "tower", "farm", "mine"], dimension: "3D", style: ["low-poly", "medieval", "fantasy", "isometric"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["building", "environment", "prop"], gameGenres: ["strategy", "rts"] },
    { id: "cyberpunk-game-kit", name: "Cyberpunk Game Kit", sourceUrl: pack("cyberpunkgamekit"), description: "Cyberpunk game kit with animated character/enemies, platforms, turrets, neon props, pickups and computer equipment.", categories: ["3D", "Game Kit", "Cyberpunk"], tags: ["cyberpunk", "sci-fi", "character", "enemy", "turret", "neon", "computer", "platform"], dimension: "3D", style: ["low-poly", "cyberpunk", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "weapon", "environment", "prop"], gameGenres: ["action", "platformer", "sci-fi"], animated: true },
    { id: "platformer-game-kit", name: "Platformer Game Kit", sourceUrl: ROOT, description: "Platformer-focused game kit with character, enemies, modular environment, collectibles, powerups, props and UI-like game objects.", categories: ["3D", "Game Kit", "Platformer"], tags: ["platformer", "character", "enemy", "modular", "collectible", "powerup", "coin", "gem"], dimension: "3D", style: ["low-poly", "cartoon"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "environment", "prop"], gameGenres: ["platformer"], animated: true },
    { id: "pirate-kit", name: "Pirate Kit", sourceUrl: ROOT, description: "Pirate game kit with characters, skeleton enemies, ships, cannons, docks, swords, sharks and vegetation.", categories: ["3D", "Game Kit", "Pirate"], tags: ["pirate", "ship", "skeleton", "cannon", "dock", "sword", "shark", "character"], dimension: "3D", style: ["low-poly", "pirate"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "vehicle", "weapon", "environment"], gameGenres: ["adventure", "action"] },
    { id: "cube-world-kit", name: "Cube World Kit", sourceUrl: ROOT, description: "Blocky world kit with characters, animals, monsters, vegetation and modular cube terrain pieces.", categories: ["3D", "Game Kit"], tags: ["cube", "voxel", "block", "character", "animal", "monster", "terrain"], dimension: "3D", style: ["low-poly", "voxel", "blocky"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "enemy", "environment", "animal"], gameGenres: ["survival", "sandbox", "adventure"], animated: true },
    { id: "sushi-restaurant-kit", name: "Sushi Restaurant Kit", sourceUrl: ROOT, description: "Restaurant game kit with kitchen/interior props, food, characters, animals and delivery-style vehicle assets.", categories: ["3D", "Game Kit", "Restaurant"], tags: ["restaurant", "kitchen", "interior", "food", "sushi", "character", "truck"], dimension: "3D", style: ["low-poly", "cartoon"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "prop", "environment", "vehicle", "food"], gameGenres: ["simulation", "casual"] },
    { id: "ultimate-modular-women", name: "Ultimate Modular Women Pack", sourceUrl: ROOT, description: "Modular animated women characters with mix-and-match outfits spanning casual, fantasy, worker, soldier and sci-fi themes.", categories: ["3D", "Characters"], tags: ["character", "woman", "female", "modular", "animated", "soldier", "sci-fi", "fantasy"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character", "clothing"], gameGenres: ["rpg", "action", "adventure"], animated: true },
    { id: "ultimate-modular-men", name: "Ultimate Modular Men Pack", sourceUrl: pack("ultimatemodularcharacters"), description: "11 modular male characters with swappable parts and animations across soldier, farmer, explorer, sci-fi and medieval themes.", categories: ["3D", "Characters"], tags: ["character", "man", "male", "modular", "animated", "soldier", "sci-fi", "medieval"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character"], gameGenres: ["rpg", "action", "adventure"], animated: true },
    { id: "ultimate-modular-ruins", name: "Ultimate Modular Ruins Pack", sourceUrl: pack("ultimatemodularruins"), categories: ["3D", "Environment"], tags: ["ruins", "dungeon", "modular", "props"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "prop", "character"], gameGenres: ["rpg", "dungeon-crawler"], animated: true },
    { id: "ultimate-spaceships", name: "Ultimate Spaceships Pack", sourceUrl: ROOT, categories: ["3D", "Vehicles", "Space"], tags: ["spaceship", "space", "sci-fi", "vehicle", "robot"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["vehicle", "prop"], gameGenres: ["sci-fi", "shooter"] },
    { id: "survival-pack", name: "Survival Pack", sourceUrl: ROOT, categories: ["3D", "Survival"], tags: ["survival", "medical", "first-aid", "tent", "camp", "gun", "knife", "flashlight", "raft"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["prop", "weapon", "environment"], gameGenres: ["survival", "adventure"] },
    { id: "ultimate-house-interior", name: "Ultimate House Interior Pack", sourceUrl: ROOT, categories: ["3D", "Interior"], tags: ["house", "interior", "furniture", "kitchen", "bathroom", "bed", "door"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "furniture", "prop"], gameGenres: ["simulation", "horror", "adventure"] },
    { id: "ultimate-guns", name: "Ultimate Guns Pack", sourceUrl: ROOT, categories: ["3D", "Weapons"], tags: ["gun", "fps", "rifle", "shotgun", "pistol", "smg", "sniper"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["weapon"], gameGenres: ["shooter", "action"] },
    { id: "animated-tanks", name: "Animated Tanks Pack", sourceUrl: ROOT, categories: ["3D", "Vehicles"], tags: ["tank", "vehicle", "war", "military", "animated"], dimension: "3D", style: ["low-poly", "military"], formats: ["fbx", "obj", "blend"], assetTypes: ["vehicle"], gameGenres: ["shooter", "strategy"], animated: true },
    { id: "modular-train", name: "Modular Train Pack", sourceUrl: ROOT, categories: ["3D", "Vehicles"], tags: ["train", "vehicle", "rail", "track", "modular", "transport"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["vehicle", "environment"], gameGenres: ["simulation"] },
    { id: "public-transport", name: "Public Transport Pack", sourceUrl: ROOT, categories: ["3D", "Vehicles", "City"], tags: ["bus", "ambulance", "taxi", "bike", "bicycle", "traffic", "vehicle", "city"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["vehicle"], gameGenres: ["simulation", "racing"] },
    { id: "modular-streets", name: "Modular Streets Pack", sourceUrl: ROOT, categories: ["3D", "Environment", "City"], tags: ["street", "road", "city", "bridge", "ramp", "sign", "modular"], dimension: "3D", style: ["low-poly", "urban"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "road", "prop"], gameGenres: ["racing", "simulation", "open-world"] },
    { id: "cars-pack", name: "Cars Pack", sourceUrl: pack("cars"), categories: ["3D", "Vehicles"], tags: ["car", "vehicle", "transport", "police", "taxi"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["vehicle"], gameGenres: ["racing"] },
    { id: "rpg-characters", name: "RPG Character Pack", sourceUrl: pack("rpgcharacters"), categories: ["3D", "Characters"], tags: ["character", "rpg", "fantasy", "rigged"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character"], gameGenres: ["rpg"], animated: true },
    { id: "animated-knight", name: "Animated Knight Pack", sourceUrl: pack("knightcharacter"), categories: ["3D", "Characters"], tags: ["knight", "character", "sword", "armor"], dimension: "3D", style: ["low-poly", "medieval"], formats: ["fbx", "obj", "blend"], assetTypes: ["character", "weapon"], gameGenres: ["rpg", "action"], animated: true },
    { id: "ultimate-animated-characters", name: "Ultimate Animated Character Pack", sourceUrl: pack("ultimatedanimatedcharacter"), categories: ["3D", "Characters"], tags: ["character", "animated", "npc", "human", "zombie", "wizard", "viking"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["character"], gameGenres: ["rpg", "adventure"], animated: true },
    { id: "modular-medieval-buildings", name: "Modular Medieval Building Pack", sourceUrl: pack("modularmedievalbuildings"), categories: ["3D", "Environment"], tags: ["medieval", "building", "modular"], dimension: "3D", style: ["low-poly", "medieval"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "building"], gameGenres: ["rpg", "strategy"] },
    { id: "modular-platformer", name: "Modular Platformer Pack", sourceUrl: pack("modularplatformer"), categories: ["3D", "Platformer"], tags: ["platformer", "modular", "environment", "collectible"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "platform"], gameGenres: ["platformer"] },
    { id: "rpg-essentials", name: "RPG Essentials Pack", sourceUrl: pack("rpg"), categories: ["3D", "RPG"], tags: ["rpg", "props", "weapons", "medieval", "fantasy"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend"], assetTypes: ["prop", "weapon", "environment"], gameGenres: ["rpg"] },
    { id: "ultimate-nature", name: "Ultimate Nature Pack", sourceUrl: pack("ultimatenature"), categories: ["3D", "Environment"], tags: ["nature", "tree", "rock", "plant", "forest"], dimension: "3D", style: ["low-poly", "nature"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "vegetation", "prop"] },
    { id: "ultimate-stylized-nature", name: "Ultimate Stylized Nature Pack", sourceUrl: pack("ultimatestylizednature"), categories: ["3D", "Environment"], tags: ["nature", "stylized", "tree", "rock", "flower", "bush"], dimension: "3D", style: ["stylized", "nature"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["environment", "vegetation"] }
  ],
  { verificationStatus: "verified", verifiedAt: "2026-08-16T00:00:00.000Z" }
);
