import { createCc0CatalogProvider } from "./catalog.js";

export const quaterniusProvider = createCc0CatalogProvider(
  "quaternius",
  "Quaternius",
  "https://quaternius.com/faq.html",
  [
    { id: "modular-medieval-buildings", name: "Modular Medieval Building Pack", sourceUrl: "https://quaternius.com/packs/modularmedievalbuildings.html", categories: ["3D", "Environment"], tags: ["medieval", "building", "modular"], dimension: "3D", style: ["low-poly", "medieval"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "building"], gameGenres: ["rpg", "strategy"] },
    { id: "modular-platformer", name: "Modular Platformer Pack", sourceUrl: "https://quaternius.com/packs/modularplatformer.html", categories: ["3D", "Platformer"], tags: ["platformer", "modular", "environment"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "platform"], gameGenres: ["platformer"] },
    { id: "modular-scifi-megakit", name: "Modular Sci-Fi Megakit", sourceUrl: "https://quaternius.com/packs/modularscifimegakit.html", categories: ["3D", "Sci-Fi"], tags: ["sci-fi", "modular", "environment"], dimension: "3D", style: ["low-poly", "sci-fi"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["environment", "building", "prop"], gameGenres: ["sci-fi", "shooter"] },
    { id: "rpg-essentials", name: "RPG Essentials Pack", sourceUrl: "https://quaternius.com/packs/rpg.html", categories: ["3D", "RPG"], tags: ["rpg", "props", "weapons"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend"], assetTypes: ["prop", "weapon", "environment"], gameGenres: ["rpg"] },
    { id: "ultimate-nature", name: "Ultimate Nature Pack", sourceUrl: "https://quaternius.com/packs/ultimatenature.html", categories: ["3D", "Environment"], tags: ["nature", "tree", "rock", "plant"], dimension: "3D", style: ["low-poly", "nature"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "vegetation", "prop"] },
    { id: "stylized-nature-megakit", name: "Stylized Nature MegaKit", sourceUrl: "https://quaternius.com/packs/stylizednaturemegakit.html", categories: ["3D", "Environment"], tags: ["nature", "stylized", "tree", "plant", "rock"], engine: ["godot", "unity", "unreal"], dimension: "3D", style: ["stylized", "nature"], formats: ["fbx", "obj", "gltf", "blend"], assetTypes: ["environment", "vegetation", "prop", "shader"], gameGenres: ["adventure", "rpg"] },
    { id: "ultimate-stylized-nature", name: "Ultimate Stylized Nature Pack", sourceUrl: "https://quaternius.com/packs/ultimatestylizednature.html", categories: ["3D", "Environment"], tags: ["nature", "stylized", "tree", "rock"], dimension: "3D", style: ["stylized", "nature"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["environment", "vegetation"] },
    { id: "cars-pack", name: "Cars Pack", sourceUrl: "https://quaternius.com/packs/cars.html", categories: ["3D", "Vehicles"], tags: ["car", "vehicle", "transport"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["vehicle"], gameGenres: ["racing"] },
    { id: "rpg-characters", name: "RPG Character Pack", sourceUrl: "https://quaternius.com/packs/rpgcharacters.html", categories: ["3D", "Characters"], tags: ["character", "rpg", "fantasy", "rigged"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character"], gameGenres: ["rpg"], animated: true },
    { id: "animated-knight", name: "Animated Knight Pack", sourceUrl: "https://quaternius.com/packs/knightcharacter.html", categories: ["3D", "Characters"], tags: ["knight", "character", "sword", "armor"], dimension: "3D", style: ["low-poly", "medieval"], formats: ["fbx", "obj", "blend"], assetTypes: ["character", "weapon"], gameGenres: ["rpg", "action"], animated: true },
    { id: "ultimate-animated-characters", name: "Ultimate Animated Character Pack", sourceUrl: "https://quaternius.com/packs/ultimatedanimatedcharacter.html", categories: ["3D", "Characters"], tags: ["character", "animated", "npc"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend"], assetTypes: ["character"], gameGenres: ["rpg", "adventure"], animated: true },
    { id: "ultimate-modular-men", name: "Ultimate Modular Men Pack", sourceUrl: "https://quaternius.com/packs/ultimatemodularcharacters.html", categories: ["3D", "Characters"], tags: ["character", "modular", "animated"], dimension: "3D", style: ["low-poly"], formats: ["fbx", "obj", "blend", "gltf"], assetTypes: ["character"], animated: true },
    { id: "ultimate-modular-ruins", name: "Ultimate Modular Ruins Pack", sourceUrl: "https://quaternius.com/packs/ultimatemodularruins.html", categories: ["3D", "Environment"], tags: ["ruins", "dungeon", "modular", "props"], dimension: "3D", style: ["low-poly", "fantasy"], formats: ["fbx", "obj", "blend"], assetTypes: ["environment", "prop", "character"], gameGenres: ["rpg", "dungeon-crawler"], animated: true }
  ]
);
