import type { ResourceRecord } from "./types.js";

export const ECOSYSTEM_REGISTRY: ResourceRecord[] = [
  {
    id: "godot-engine",
    name: "Godot Engine",
    kind: "code",
    source: "Godot Engine",
    sourceUrl: "https://github.com/godotengine/godot",
    license: "MIT",
    licenseSource: "https://github.com/godotengine/godot/blob/master/LICENSE.txt",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["engine", "godot", "2d", "3d", "c++", "gdscript", "open-source"],
    notes: "Core Godot Engine is MIT licensed. Third-party components are documented separately in COPYRIGHT.txt."
  },
  {
    id: "phaser-engine",
    name: "Phaser",
    kind: "code",
    source: "Phaser Studio",
    sourceUrl: "https://github.com/phaserjs/phaser",
    license: "MIT",
    licenseSource: "https://github.com/phaserjs/phaser/blob/master/LICENSE.md",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["engine", "phaser", "web", "html5", "2d", "javascript", "typescript"],
    notes: "Phaser framework code is MIT. Example/media assets must be reviewed separately where applicable."
  },
  {
    id: "babylonjs",
    name: "Babylon.js",
    kind: "code",
    source: "Babylon.js",
    sourceUrl: "https://github.com/BabylonJS/Babylon.js",
    license: "Apache-2.0",
    licenseSource: "https://github.com/BabylonJS/Babylon.js",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["engine", "web", "3d", "webgl", "webgpu", "webxr", "typescript", "rendering"],
    notes: "Permissive Apache-2.0 web 3D/game engine. Review imported demo assets separately."
  },
  {
    id: "threejs",
    name: "three.js",
    kind: "code",
    source: "three.js",
    sourceUrl: "https://github.com/mrdoob/three.js",
    license: "MIT",
    licenseSource: "https://github.com/mrdoob/three.js/blob/dev/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["web", "3d", "webgl", "webgpu", "rendering", "javascript", "library"],
    notes: "Core package is MIT. Some examples/addons or bundled example assets may carry separate notices; inspect copied example material before reuse."
  },
  {
    id: "pixijs",
    name: "PixiJS",
    kind: "code",
    source: "PixiJS",
    sourceUrl: "https://github.com/pixijs/pixijs",
    license: "MIT",
    licenseSource: "https://github.com/pixijs/pixijs/blob/dev/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["web", "2d", "webgl", "renderer", "typescript", "javascript", "graphics"],
    notes: "MIT licensed 2D rendering engine. Community filters/plugins may have their own repositories/licenses."
  },
  {
    id: "matter-js",
    name: "Matter.js",
    kind: "code",
    source: "Matter.js",
    sourceUrl: "https://github.com/liabru/matter-js",
    license: "MIT",
    licenseSource: "https://github.com/liabru/matter-js/blob/master/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["physics", "2d", "web", "javascript", "rigid-body", "collision"],
    notes: "MIT licensed 2D rigid-body physics engine for web games and simulations."
  },
  {
    id: "libgdx",
    name: "libGDX",
    kind: "code",
    source: "libGDX",
    sourceUrl: "https://github.com/libgdx/libgdx",
    license: "Apache-2.0",
    licenseSource: "https://github.com/libgdx/libgdx",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["engine", "framework", "java", "android", "desktop", "ios", "web", "2d", "3d"],
    notes: "Official project states libGDX is Apache-2.0 and supports unrestricted commercial/non-commercial use."
  },
  {
    id: "raylib",
    name: "raylib",
    kind: "code",
    source: "raylib",
    sourceUrl: "https://github.com/raysan5/raylib",
    license: "Zlib",
    licenseSource: "https://github.com/raysan5/raylib/blob/master/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: false,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["engine", "framework", "c", "c++", "2d", "3d", "desktop", "webassembly", "prototype"],
    notes: "raylib uses the zlib/libpng license and explicitly permits commercial applications. Embedded third-party dependencies retain their own notices."
  },
  {
    id: "bevy-assets-ecosystem",
    name: "Bevy community assets and plugins",
    kind: "code",
    source: "Bevy ecosystem",
    sourceUrl: "https://bevy.org/assets/",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["bevy", "rust", "plugins", "ecs", "physics", "ui", "networking", "assets"],
    notes: "Community ecosystem index. Inspect each crate/repository license and bundled assets separately."
  },
  {
    id: "godot-shaders",
    name: "Godot shader ecosystem",
    kind: "code",
    source: "Godot community",
    sourceUrl: "https://godotshaders.com/",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["godot", "shader", "vfx", "canvas-item", "spatial", "visual-effects"],
    notes: "High-value shader discovery source. License must be checked on each shader/source page before reuse."
  },
  {
    id: "shadertoy",
    name: "Shadertoy",
    kind: "code",
    source: "Shadertoy",
    sourceUrl: "https://www.shadertoy.com/",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "account",
    tags: ["shader", "glsl", "vfx", "procedural", "rendering", "reference"],
    notes: "Excellent shader reference/discovery source, but authorship/license varies. Do not copy shader code without explicit permission/license verification."
  },
  {
    id: "unity-official-samples",
    name: "Unity official samples and technologies",
    kind: "project",
    source: "Unity Technologies",
    sourceUrl: "https://github.com/Unity-Technologies",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["unity", "samples", "starter", "rendering", "dots", "netcode", "urp", "hdrp"],
    notes: "Official Unity repositories use different licenses including Unity-specific terms. Verify LICENSE in the exact repository before reuse."
  },
  {
    id: "unreal-samples",
    name: "Unreal Engine samples and plugins",
    kind: "project",
    source: "Epic Games / Unreal ecosystem",
    sourceUrl: "https://www.unrealengine.com/marketplace/en-US/content-cat/assets/code-plugins",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "account",
    tags: ["unreal", "ue5", "plugin", "samples", "blueprint", "c++", "rendering", "networking"],
    notes: "Engine-specific marketplace/sample ecosystem under Epic/Unreal terms. Require exact item/EULA review."
  }
];
