import type { ResourceRecord } from "./types.js";

/**
 * Broad discovery sources. Uniform-license sources may be classified directly;
 * multi-license/proprietary ecosystems deliberately fail closed to per-item review.
 */
export const EXPANDED_REGISTRY: ResourceRecord[] = [
  {
    id: "ambientcg",
    name: "ambientCG",
    kind: "asset",
    source: "ambientCG",
    sourceUrl: "https://ambientcg.com/",
    license: "CC0-1.0",
    licenseSource: "https://ambientcg.com/license",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: false,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["3d", "pbr", "textures", "materials", "hdris", "models", "cc0", "environment"],
    notes: "Official site states all assets are CC0 and usable commercially without attribution. Prefer canonical asset pages and official downloads."
  },
  {
    id: "google-fonts-all",
    name: "Google Fonts",
    kind: "asset",
    source: "Google Fonts",
    sourceUrl: "https://fonts.google.com/",
    license: "MULTIPLE",
    licenseSource: "https://developers.google.com/fonts/",
    commercialUse: true,
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["font", "fonts", "ui", "typography", "open-source", "cjk"],
    notes: "Google states all Google Fonts are open source and may be used commercially. Exact font-family license and Reserved Font Name obligations must still be preserved per family."
  },
  {
    id: "tabler-icons",
    name: "Tabler Icons",
    kind: "asset",
    source: "Tabler",
    sourceUrl: "https://tabler.io/icons",
    license: "MIT",
    licenseSource: "https://tabler.io/icons",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["2d", "icons", "svg", "ui", "hud", "vector", "mit"],
    notes: "Large open-source SVG icon set; the free source package is MIT licensed."
  },
  {
    id: "bevy-engine",
    name: "Bevy Engine and examples",
    kind: "code",
    source: "Bevy",
    sourceUrl: "https://github.com/bevyengine/bevy",
    license: "MIT OR Apache-2.0",
    licenseSource: "https://github.com/bevyengine/bevy/blob/main/README.md",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["code", "rust", "engine", "ecs", "3d", "2d", "examples"],
    notes: "Bevy code is dual MIT/Apache-2.0 except where noted. Example assets carry separate licenses in CREDITS.md and must be reviewed separately."
  },
  {
    id: "godot-asset-library",
    name: "Godot Asset Library",
    kind: "code",
    source: "Godot Engine",
    sourceUrl: "https://godotengine.org/asset-library/asset",
    license: "MULTIPLE",
    licenseSource: "https://docs.godotengine.org/en/stable/community/asset_library/using_assetlib.html",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["godot", "plugin", "addon", "code", "shader", "tool", "template", "asset-library"],
    notes: "Official Godot Asset Library exposes the license per asset. Browse/download does not require login; every asset license must be inspected before reuse."
  },
  {
    id: "openverse",
    name: "Openverse",
    kind: "asset",
    source: "Openverse",
    sourceUrl: "https://openverse.org/",
    license: "MULTIPLE",
    licenseSource: "https://docs.openverse.org/",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["images", "audio", "creative-commons", "public-domain", "search", "open-content"],
    notes: "Open-content search aggregator. License varies by result and original source; preserve creator/source/license metadata and validate every selected item."
  },
  {
    id: "freesound",
    name: "Freesound",
    kind: "audio",
    source: "Freesound",
    sourceUrl: "https://freesound.org/",
    license: "MULTIPLE",
    licenseSource: "https://freesound.org/help/faq/",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: true,
    authType: "api_key",
    tags: ["audio", "sfx", "ambience", "foley", "music", "samples", "creative-commons"],
    notes: "Large audio library with per-sound Creative Commons licensing. API use requires credentials; do not assume all search results are commercially usable."
  },
  {
    id: "itchio-assets",
    name: "itch.io Game Assets",
    kind: "asset",
    source: "itch.io",
    sourceUrl: "https://itch.io/game-assets",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["2d", "3d", "pixel", "sprites", "tilesets", "ui", "audio", "fonts", "game-assets"],
    notes: "High-value game-asset marketplace/community. Terms vary by creator and pack; inspect the exact asset page/license before recommendation."
  },
  {
    id: "sketchfab",
    name: "Sketchfab downloadable models",
    kind: "asset",
    source: "Sketchfab",
    sourceUrl: "https://sketchfab.com/",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "account",
    tags: ["3d", "models", "characters", "vehicles", "props", "environment", "creative-commons"],
    notes: "Downloadable model licenses vary. Filter/search is useful, but the exact model license, author attribution and embedded texture rights must be checked."
  },
  {
    id: "unity-asset-store",
    name: "Unity Asset Store",
    kind: "asset",
    source: "Unity",
    sourceUrl: "https://assetstore.unity.com/",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "account",
    tags: ["unity", "3d", "2d", "code", "plugin", "shader", "vfx", "audio", "tools"],
    notes: "Large engine marketplace. Free price is not an open license; Asset Store/EULA terms and package-specific restrictions require manual review."
  },
  {
    id: "fab",
    name: "Fab",
    kind: "asset",
    source: "Epic Games Fab",
    sourceUrl: "https://www.fab.com/",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "account",
    tags: ["unreal", "unity", "3d", "materials", "characters", "environment", "plugins", "vfx", "audio"],
    notes: "Large multi-engine marketplace. License and tier terms vary; require exact listing/license review before integration."
  },
  {
    id: "pixabay-audio",
    name: "Pixabay Audio and Media",
    kind: "audio",
    source: "Pixabay",
    sourceUrl: "https://pixabay.com/",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["audio", "music", "sfx", "ambience", "images", "video"],
    notes: "Useful royalty-free media source, but governed by Pixabay Content License rather than an open-source license. Review current terms and standalone-distribution restrictions per use."
  },
  {
    id: "mixkit",
    name: "Mixkit",
    kind: "audio",
    source: "Envato Mixkit",
    sourceUrl: "https://mixkit.co/",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["music", "sfx", "video", "audio", "stock"],
    notes: "Useful free media source under custom terms. Validate the current Mixkit license for the exact asset type and intended distribution."
  },
  {
    id: "sonniss-gdc-audio",
    name: "Sonniss GDC Game Audio Bundles",
    kind: "audio",
    source: "Sonniss",
    sourceUrl: "https://sonniss.com/gameaudiogdc",
    license: "CUSTOM",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["audio", "sfx", "game-audio", "foley", "ambience", "bundle"],
    notes: "Large professional game-audio bundles. Treat as custom-license content and verify the current bundle license before shipping or redistributing source audio."
  },
  {
    id: "gltf-sample-assets",
    name: "Khronos glTF Sample Assets",
    kind: "asset",
    source: "Khronos Group",
    sourceUrl: "https://github.com/KhronosGroup/glTF-Sample-Assets",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["3d", "gltf", "models", "animation", "test-assets", "reference"],
    notes: "High-quality reference/sample models; licenses vary by model. Read each model's README/license before reuse beyond testing."
  },
  {
    id: "openmoji",
    name: "OpenMoji",
    kind: "asset",
    source: "OpenMoji",
    sourceUrl: "https://openmoji.org/",
    license: "CC-BY-SA-4.0",
    licenseSource: "https://openmoji.org/about/",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: true,
    apiRequired: false,
    authType: "none",
    tags: ["icons", "emoji", "svg", "png", "ui", "vector"],
    notes: "Commercially usable with attribution/share-alike obligations. Keep separate from permissive icon sets when share-alike is disallowed."
  },
  {
    id: "heroicons",
    name: "Heroicons",
    kind: "asset",
    source: "Tailwind Labs",
    sourceUrl: "https://heroicons.com/",
    license: "MIT",
    licenseSource: "https://github.com/tailwindlabs/heroicons/blob/master/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["icons", "svg", "ui", "hud", "vector", "mit"],
    notes: "Permissive general-purpose interface icon source."
  },
  {
    id: "feather-icons",
    name: "Feather Icons",
    kind: "asset",
    source: "Feather",
    sourceUrl: "https://feathericons.com/",
    license: "MIT",
    licenseSource: "https://github.com/feathericons/feather/blob/main/LICENSE",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["icons", "svg", "ui", "vector", "mit"],
    notes: "Small clean MIT icon set useful for game tooling and minimalist HUDs."
  },
  {
    id: "bootstrap-icons",
    name: "Bootstrap Icons",
    kind: "asset",
    source: "Bootstrap",
    sourceUrl: "https://icons.getbootstrap.com/",
    license: "MIT",
    licenseSource: "https://github.com/twbs/icons/blob/main/LICENSE.md",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["icons", "svg", "ui", "web", "vector", "mit"],
    notes: "Broad general-purpose MIT SVG icon library."
  },
  {
    id: "font-awesome-free",
    name: "Font Awesome Free",
    kind: "asset",
    source: "Font Awesome",
    sourceUrl: "https://fontawesome.com/",
    license: "MULTIPLE",
    licenseSource: "https://fontawesome.com/license/free",
    commercialUse: true,
    modification: "unknown",
    redistribution: true,
    attribution: "unknown",
    shareAlike: false,
    apiRequired: false,
    authType: "none",
    tags: ["icons", "svg", "font", "ui", "webfont"],
    notes: "Free distribution uses different licenses for icons/fonts/code. Preserve component-specific license obligations rather than flattening to one license."
  },
  {
    id: "noto-fonts",
    name: "Noto Fonts",
    kind: "asset",
    source: "Google Noto",
    sourceUrl: "https://fonts.google.com/noto",
    license: "OFL-1.1",
    licenseSource: "https://github.com/notofonts",
    commercialUse: true,
    modification: true,
    redistribution: true,
    attribution: true,
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["font", "cjk", "chinese", "japanese", "korean", "unicode", "ui", "localization"],
    notes: "High-value multilingual/CJK font family ecosystem. Verify the exact family license file and Reserved Font Names before modifying/redistributing font software."
  },
  {
    id: "github-game-engines",
    name: "GitHub game engines and frameworks",
    kind: "code",
    source: "GitHub",
    sourceUrl: "https://github.com/topics/game-engine",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["code", "engine", "framework", "ecs", "rendering", "physics", "game-development"],
    notes: "Discovery seed only. Inspect repository license, dependencies and bundled assets before recommendation."
  },
  {
    id: "github-game-templates",
    name: "GitHub game templates and starters",
    kind: "project",
    source: "GitHub",
    sourceUrl: "https://github.com/topics/game-template",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["starter", "template", "boilerplate", "godot", "unity", "unreal", "phaser", "bevy"],
    notes: "Discovery seed only. Repository code license does not automatically cover included art/audio/fonts."
  },
  {
    id: "github-game-shaders",
    name: "GitHub game shaders and VFX",
    kind: "code",
    source: "GitHub",
    sourceUrl: "https://github.com/topics/shader",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["shader", "vfx", "glsl", "hlsl", "godot", "unity", "unreal", "rendering"],
    notes: "Discovery seed only. Inspect repository license and copied shader provenance before integration."
  },
  {
    id: "github-game-systems",
    name: "GitHub reusable game systems",
    kind: "code",
    source: "GitHub",
    sourceUrl: "https://github.com/topics/gamedev",
    license: "MULTIPLE",
    commercialUse: "unknown",
    modification: "unknown",
    redistribution: "unknown",
    attribution: "unknown",
    shareAlike: "unknown",
    apiRequired: false,
    authType: "none",
    tags: ["inventory", "combat", "ai", "pathfinding", "procedural", "save", "networking", "dialogue", "crafting", "code"],
    notes: "Broad discovery seed for reusable systems. Always inspect the explicit repository license and dependency licenses."
  }
];
